### ISSUE TITLE
python3 test.py err

### ISSUE THREAD

**Issue by zhang261007** [krichelj/PyDiffGame#12]
in line 172 in PyDiffGame.py should it be as:
 A_cl = self.__A - SP_sum
to make A be found by object.

While thanks for your graceful work，I'm new to the diffgame, please could tell more about the differential equation the example used? As dx/dt = Ax + Bu,the meaning in reality?
Could you please give some advice about how to deal with the pursuit/evasion scenarios like two cars with acc and thi controlling?

**Comment by krichelj** [comment]
Thank you for your comment about line 172 - fixed in the latest commit.
About the theory being the model presented - a basic intro is presented in the readme files,
I suggest reading it. 

About pursuit/evasion scenarios as you mentioned - I'm not sure we currently support these cases.
Can you be more specific?

**Comment by zhang261007** [comment]
Thanks for you apply. I.ve read the readme and the math, alse dealling with Riccati equation by hand.
First, just wondering the differential equation form in the Tutorial, as 

`A = np.array([[-2, 1],
              [1, 4]])
B = [np.array([[1, 0],
               [0, 1]]),
     np.array([[0],
               [1]]),
     np.array([[1],
               [0]])]
X0 = np.array([10, 20])`

What's the meaning of them in the real world?

What's more, I shouldn't bother you for asking using diff-game in Bicycle Model in car. Should learn more about these two first.
Thanks.

**Comment by krichelj** [comment]
@zhang261007 
`PyDiffGame` is intended for applying control on linear systems, when the modeling is done using the state space representation.

In general terms, the main concept at hand is the differential equation you mentioned. The matrix `A` is the system dynamics matrix - it defines the autonomous behavior of the system when no input is fed to it.  The matrix `B` is the input coefficients matrix - it defines the relations between the inputs to the differential model of the system and `X0` is the initial vector of the variable `X`, as we are solving a differential equation and therefore need an initial condition.

Here you can find a relevant Wikipedia entry for further reading:
[https://en.wikipedia.org/wiki/State-space_representation#Linear_systems](https://en.wikipedia.org/wiki/State-space_representation#Linear_systems)

**Comment by zhang261007** [comment]
Thanks, and maybe as poor as my expression.
 I know the math meaning of these matrix. I just wanna know what model A = np.array([[-2, 1], [1, 4]]) meaning, like pendulum , acrobots，Cart-Poles, or Quadrotors ?
Simple car as dxp=vpcosφp,dyp=vpsinφp. I wanna know the number [[-2, 1], [1, 4]] meaning in the real world.

**Comment by krichelj** [comment]
@zhang261007 
These values are purely experimental and are meant to simulate the package functions.
If you have any actual values you would like to simulate and need any help, please comment further.

Thanks
