### ISSUE TITLE
Quadpy requires a license

### ISSUE THREAD

**Issue by txw226** [krichelj/PyDiffGame#17]
It seems that PyDiffGame is unusable without purchasing a quadpy license. Upon running any PyDiffGame example I get this message:

Warning: Unable to find valid license for product ID 06b7db1d-5a40-4d2c-b89c-6b1887c377c1.
Enter license key:

From this forum it appears the product asking for a license is quadpy: https://github.com/sigma-py/quadpy/issues/463. Uninstalling and reinstalling the packages mentioned in the forum did not get rid of the license prompt.

**Comment by txw226** [comment]
I got past this error by removing quadpy from DiscretePyDiffGame.py. I replaced quadpy.quad() with scipy.integrate.quad(). I can't tell if the result is the same though

**Comment by krichelj** [comment]
Adopted the suggested solution and committed in 05766f6e4a722ea4b8e2e36827fccaff5d225750
